{
 "title": "Temporal Core SDK (OTel) Metrics",
 "description": "Temporal SDKs \n",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# CPU placeholder\n\nMetrics from the Temporal SDK should be complemented with the workers' CPU and memory usage statistics."
   }
  },
  {
   "title": "Memory usage",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "# Memory placeholder\n\nMetrics from the Temporal SDK should be complemented with the workers' CPU and memory usage statistics."
   }
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RPC Requests Vs Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_total{namespace=~\"$namespace\", namespace!=\"none\"}[$__rate_interval])) by (namespace)\n",
     "legendFormat": "[request] namespace: {{ namespace }}"
    },
    {
     "expr": "sum(rate(temporal_request_failure_total{namespace=~\"$namespace\", namespace!=\"none\"}[$__rate_interval])) by (namespace)\n",
     "legendFormat": "[failure] namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "RPC Failures Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_failure_total{namespace=~\"$namespace\", namespace!=\"none\"}[$__rate_interval])) by (namespace, operation)\n",
     "legendFormat": "namespace: {{ namespace }}; operation:{{operation}}"
    }
   ]
  },
  {
   "title": "RPC Requests Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_request_total{namespace=~\"$namespace\", namespace!=\"none\"}[$__rate_interval])) by (namespace, operation)\n",
     "legendFormat": "namespace: {{ namespace }}; operation:{{operation}}"
    }
   ]
  },
  {
   "title": "RPC Latencies (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, operation, le) (rate(temporal_request_latency_bucket{namespace=~\"$namespace\" }[$__rate_interval])))\n",
     "legendFormat": "namespace: {{ namespace }}; operation: {{ operation }}"
    }
   ]
  },
  { "title": "Long Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Long RPC Failures Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_long_request_failure_total{namespace=~\"$namespace\", namespace!=\"none\"}[$__rate_interval])) by (namespace, operation)\n",
     "legendFormat": "namespace: {{ namespace }}; operation:{{operation}}"
    }
   ]
  },
  {
   "title": "Long RPC Latencies (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, operation, le) (rate(temporal_long_request_latency_bucket{namespace=~\"$namespace\" }[$__rate_interval])))\n",
     "legendFormat": "namespace: {{ namespace }}; operation: {{ operation }}"
    }
   ]
  },
  { "title": "Workflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Workflow Completion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_completed_total{namespace=~\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "namespace:{{namespace}}; WorkflowType {{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow End-To-End Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, workflow_type, le) (rate(temporal_workflow_endtoend_latency_bucket{namespace=~\"$namespace\"}[$__rate_interval])))\n",
     "legendFormat": "namespace:{{namespace}}; WorkflowType {{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow Failures By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_failed_total{namespace=~\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "namespace:{{namespace}}; WorkflowType {{workflow_type}}"
    }
   ]
  },
  { "title": "Workflow Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Workflow Task Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (rate(temporal_workflow_task_queue_poll_succeed_total{namespace=~\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "namespace: {{ namespace }}; task_queue:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Workflow Task Schedule To Start (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, task_queue,  le) (rate(temporal_workflow_task_schedule_to_start_latency_bucket{namespace=~\"$namespace\"}[$__rate_interval])))\n",
     "legendFormat": "namespace: {{ namespace }}; task_queue:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Workflow Task Failed ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_task_execution_failed_total{namespace=~\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "namespace: {{ namespace }}; workflow_type:{{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow Task Execution Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, workflow_type,  le) (rate(temporal_workflow_task_execution_latency_bucket{namespace=~\"$namespace\"}[$__rate_interval])))\n",
     "legendFormat": "namespace: {{ namespace }}; workflow_type:{{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow Task Replay Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, workflow_type, le) (rate(temporal_workflow_task_replay_latency_bucket{namespace=~\"$namespace\"}[$__rate_interval])))\n",
     "legendFormat": "namespace: {{ namespace }}; workflow_type:{{workflow_type}}"
    }
   ]
  },
  {
   "title": "Workflow Task Empty Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (rate(temporal_workflow_task_queue_poll_empty_total{namespace=~\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "namespace: {{ namespace }}; task_queue:{{task_queue}}"
    }
   ]
  },
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Activity Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(temporal_activity_schedule_to_start_latency_count{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Activity Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, activity_type) (rate(temporal_activity_execution_failed_total{namespace=~\"$namespace\"}[$__rate_interval]))\n",
     "legendFormat": "namespace: {{ namespace }}; activity_type:{{activity_type}}"
    }
   ]
  },
  {
   "title": "Activity Execution Latencies (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, activity_type , le) (rate(temporal_activity_execution_latency_bucket{namespace=~\"$namespace\"}[$__rate_interval])))\n",
     "legendFormat": "namespace: {{ namespace }}; activity_type:{{activity_type}}"
    }
   ]
  },
  { "title": "Activity Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Empty Activity Polls ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (rate(temporal_activity_poll_no_task_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "namespace: {{ namespace }}; task_queue:{{task_queue}}"
    }
   ]
  },
  {
   "title": "Activity Schedule To Start (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, task_queue , le) (rate(temporal_activity_schedule_to_start_latency_bucket{namespace=~\"$namespace\"}[$__rate_interval])))\n",
     "legendFormat": "namespace: {{ namespace }}; task_queue:{{task_queue}}"
    }
   ]
  },
  { "title": "Slots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Slots Available",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_worker_task_slots_available{namespace=~\"$namespace\"}",
     "legendFormat": "namespace: {{ namespace }}; worker_type:{{worker_type}}"
    }
   ]
  },
  {
   "title": "Slots Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_worker_task_slots_used{namespace=~\"$namespace\"}",
     "legendFormat": "namespace: {{ namespace }}; worker_type:{{worker_type}}"
    }
   ]
  },
  { "title": "Sticky Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Sticky Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "temporal_sticky_cache_size{namespace=~\"$namespace\"}",
     "legendFormat": "namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Sticky Cache Forced Eviction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(temporal_sticky_cache_total_forced_eviction_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "namespace: {{ namespace }}; "
    }
   ]
  },
  {
   "title": "Sticky Cache Hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(temporal_sticky_cache_hit_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Sticky Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace, task_queue) (rate(temporal_sticky_cache_miss_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "namespace: {{ namespace }}; task_queue:{{task_queue}}"
    }
   ]
  }
 ]
}